# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3000:3000"
    command: npm run server
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db