export enum NotificationActionTypes {
  NOTIFICATION_ADD_MESSAGE = 'NOTIFICATION/ADD_MESSAGE',
  NOTIFICATION_DELETE_MESSAGES = 'NOTIFICATION/DELETE_MESSAGES',
  NOTIFICATION_NEXT_MESSAGE = 'NOTIFICATION/NEXT_MESSAGE'
}
