// Getters (GET*)
// [CONTEXT]_[ACTION]_[PROPERTY]

// Reducer (SET*, ADD*, REMOVE*)
// [CONTEXT]_[ACTION]_[PROPERTY]

// Actions (FETCH*, CREATE*, UPDATE*, DELETE*)
// [CONTEXT]_[ACTION]_[PROPERTY]_[STATUS]
export const UI_ENABLE_LOADING = 'UI_ENABLE_LOADING';
export const UI_DISABLE_LOADING = 'UI_DISABLE_LOADING';
export const UI_TOGGLE_LOADING = 'UI_TOGGLE_LOADING';
